export const MAIN_SET_TITLE_TYPE = "MAIN_SET_TITLE_TYPE";

export const MAIN_SET_DESC_TYPE = "MAIN_SET_DESC_TYPE";

export const MAIN_SELECT_TYPE = "MAIN_SELECT_TYPE";

export const MAIN_FETCH_SUBMIT_START_TYPE = "MAIN_FETCH_SUBMIT_START_TYPE";

export const MAIN_FETCH_SUBMIT_END_TYPE = "MAIN_FETCH_SUBMIT_END_TYPE";

export const MAIN_FETCH_QUERY_START_TYPE = "MAIN_FETCH_QUERY_START_TYPE";

export const MAIN_FETCH_QUERY_END_TYPE = "MAIN_FETCH_QUERY_END_TYPE";

export const MAIN_FETCH_SUBMIT_TYPE = "MAIN_FETCH_SUBMIT_TYPE";

export const MAIN_FETCH_QUERY_TYPE = "MAIN_FETCH_QUERY_TYPE";

export const MAIN_FETCH_REMOVE_TYPE = "MAIN_FETCH_REMOVE_TYPE";

export const MAIN_ADD_HISTORY_TYPE = "MAIN_ADD_HISTORY_TYPE";

export const MAIN_REMOVE_HISTORY_TYPE = "MAIN_REMOVE_HISTORY_TYPE";

export const MAIN_UPDATE_HISTORY_TYPE = "MAIN_UPDATE_HISTORY_TYPE";
